<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StopsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Path to the JSON generated by extractStops.js
        $jsonPath = database_path('data/stops.json');

        if (!file_exists($jsonPath)) {
            $this->command->error("stops.json not found at {$jsonPath}");
            return;
        }

        $raw = file_get_contents($jsonPath);
        $stopsData = json_decode($raw, true);

        // Map JSON fields to your DB columns
        $inserts = array_map(function ($s) {
            return [
                'stop_id'   => $s['id'],
                'stop_name' => $s['name'],
                'stop_lat'  => $s['latitude'],
                'stop_long' => $s['longitude'],
                'county_id' => $s['county'],
                // direction_id dropped
            ];
        }, $stopsData);

        // Bulk insert into `stops` table
        DB::table('stops')
  ->upsert(
    $inserts,
    ['stop_id'],                  // unique key
    ['stop_name','stop_lat','stop_long','county_id']  // cols to update
  );

$this->command->info("Upserted " . count($inserts) . " stops.");

    }
}

